//! Build output emitter for the orv compiler.
//!
//! Generates the `dist/` directory structure:
//! ```text
//! dist/
//! ├── server.rs          (generated Rust server source)
//! ├── public/
//! │   ├── index.html     (static HTML from @html pages)
//! │   └── app.js         (client-side fetch bridges)
//! └── manifest.json      (build manifest)
//! ```

use std::fmt::Write;
use std::fs;
use std::path::{Path, PathBuf};

use orv_project::WorkspaceGraph;

/// Build manifest describing all output artifacts.
#[derive(Debug, Clone, serde::Serialize)]
pub struct BuildManifest {
    pub version: String,
    pub entry: String,
    pub outputs: Vec<BuildOutput>,
    pub routes: Vec<RouteManifestEntry>,
    pub pages: Vec<PageManifestEntry>,
}

#[derive(Debug, Clone, serde::Serialize)]
pub struct BuildOutput {
    pub kind: String,
    pub path: String,
}

#[derive(Debug, Clone, serde::Serialize)]
pub struct RouteManifestEntry {
    pub method: String,
    pub path: String,
}

#[derive(Debug, Clone, serde::Serialize)]
pub struct PageManifestEntry {
    pub owner: String,
    pub domain: String,
    pub html_file: String,
}

/// Generate client-side fetch bridge code for internal routes.
///
/// For each `FetchEdge` that references a route target, generates a typed
/// fetch function:
/// ```js
/// export async function target_fetch(params = {}) {
///   const response = await fetch('/api/users', { method: 'GET' });
///   return response.json();
/// }
/// ```
pub fn generate_fetch_bridge(graph: &WorkspaceGraph) -> String {
    let mut code = String::new();
    code.push_str("// Auto-generated by orv compiler - do not edit\n");
    code.push_str("// Fetch bridges for internal route references\n\n");

    for module in &graph.modules {
        for fetch in &module.fetches {
            // Find the matching route by path (the fetch target is the route path)
            let route = module
                .routes
                .iter()
                .find(|r| r.path == fetch.target || r.action == fetch.target);

            if let Some(route) = route {
                let fn_name = sanitize_js_name(&fetch.target);
                let method = &route.method;
                let path = &route.path;

                // Check if path has parameters
                let has_params = path.contains(':');

                let _ = writeln!(
                    code,
                    "export async function {fn_name}_fetch(params = {{}}) {{"
                );

                if has_params {
                    // Generate path with parameter substitution
                    let js_path = generate_parameterized_path(path);
                    let _ = writeln!(code, "  const url = {js_path};");
                } else {
                    let _ = writeln!(code, "  const url = '{path}';");
                }

                let _ = writeln!(code, "  const options = {{ method: '{method}' }};");

                // Add body for POST/PUT/PATCH
                if matches!(method.as_str(), "POST" | "PUT" | "PATCH") {
                    code.push_str(
                        "  if (params.body !== undefined) {\n\
                         \x20   options.headers = { 'Content-Type': 'application/json' };\n\
                         \x20   options.body = JSON.stringify(params.body);\n\
                         \x20 }\n",
                    );
                }

                code.push_str("  const response = await fetch(url, options);\n");
                code.push_str("  if (!response.ok) throw new Error(`HTTP ${response.status}`);\n");

                // Return type based on route action
                code.push_str("  return response.json();\n");
                let _ = writeln!(code, "}}\n");
            }
        }
    }

    code
}

/// Generate a parameterized path template for JavaScript.
/// `/users/:id/posts/:post_id` → `` `/users/${params.id}/posts/${params.post_id}` ``
fn generate_parameterized_path(path: &str) -> String {
    let mut result = String::from("`");
    for segment in path.split('/') {
        if segment.is_empty() {
            continue;
        }
        result.push('/');
        if let Some(param_name) = segment.strip_prefix(':') {
            let _ = write!(result, "${{params.{param_name}}}");
        } else {
            result.push_str(segment);
        }
    }
    result.push('`');
    result
}

/// Sanitize a name for use as a JavaScript identifier.
fn sanitize_js_name(name: &str) -> String {
    name.chars()
        .map(|c| {
            if c.is_alphanumeric() || c == '_' {
                c
            } else {
                '_'
            }
        })
        .collect()
}

/// Emit the build output to the given directory.
pub fn emit_build_output(
    graph: &WorkspaceGraph,
    entry_name: &str,
    output_dir: &Path,
) -> Result<EmitResult, EmitError> {
    fs::create_dir_all(output_dir).map_err(|e| EmitError::Io(e.to_string()))?;

    let public_dir = output_dir.join("public");
    fs::create_dir_all(&public_dir).map_err(|e| EmitError::Io(e.to_string()))?;

    let mut outputs = Vec::new();
    let mut route_entries = Vec::new();
    let mut page_entries = Vec::new();

    // Collect routes from all modules
    for module in &graph.modules {
        for route in &module.routes {
            route_entries.push(RouteManifestEntry {
                method: route.method.clone(),
                path: route.path.clone(),
            });
        }

        for page in &module.pages {
            page_entries.push(PageManifestEntry {
                owner: page.owner.clone(),
                domain: page.domain.clone(),
                html_file: format!("public/{}.html", slugify(&page.owner)),
            });
        }
    }

    // Generate client runtime (signals + event binding)
    let runtime_code = generate_client_runtime();
    let runtime_path = public_dir.join("orv-runtime.js");
    fs::write(&runtime_path, &runtime_code).map_err(|e| EmitError::Io(e.to_string()))?;
    outputs.push(BuildOutput {
        kind: "client-runtime".to_owned(),
        path: "public/orv-runtime.js".to_owned(),
    });

    // Generate fetch bridge
    let fetch_code = generate_fetch_bridge(graph);
    if !fetch_code.trim().is_empty() && fetch_code.lines().count() > 3 {
        let js_path = public_dir.join("app.js");
        fs::write(&js_path, &fetch_code).map_err(|e| EmitError::Io(e.to_string()))?;
        outputs.push(BuildOutput {
            kind: "fetch-bridge".to_owned(),
            path: "public/app.js".to_owned(),
        });
    }

    // Generate manifest
    let manifest = BuildManifest {
        version: "0.1.0".to_owned(),
        entry: entry_name.to_owned(),
        outputs: outputs.clone(),
        routes: route_entries,
        pages: page_entries,
    };

    let manifest_path = output_dir.join("manifest.json");
    let manifest_json =
        serde_json::to_string_pretty(&manifest).map_err(|e| EmitError::Io(e.to_string()))?;
    fs::write(&manifest_path, &manifest_json).map_err(|e| EmitError::Io(e.to_string()))?;

    outputs.push(BuildOutput {
        kind: "manifest".to_owned(),
        path: "manifest.json".to_owned(),
    });

    Ok(EmitResult {
        output_dir: output_dir.to_owned(),
        manifest_path,
        outputs,
    })
}

/// Result of a build emission.
#[derive(Debug)]
pub struct EmitResult {
    pub output_dir: PathBuf,
    pub manifest_path: PathBuf,
    pub outputs: Vec<BuildOutput>,
}

#[derive(Debug, thiserror::Error)]
pub enum EmitError {
    #[error("I/O error: {0}")]
    Io(String),
}

/// Generate the minimal client-side runtime for signal reactivity and event binding.
///
/// This runtime:
/// 1. Initializes signal state from server-rendered data attributes
/// 2. Binds event handlers declared via `data-orv-*` attributes
/// 3. Reactively updates DOM nodes when signals change
pub fn generate_client_runtime() -> String {
    r#"// orv client runtime - auto-generated, do not edit
"use strict";

const __orv = (() => {
  // Signal store
  const signals = {};
  const subscribers = {};

  function createSignal(name, initialValue) {
    signals[name] = initialValue;
    subscribers[name] = [];
  }

  function getSignal(name) {
    return signals[name];
  }

  function setSignal(name, value) {
    const prev = signals[name];
    if (prev === value) return;
    signals[name] = value;
    // Notify subscribers
    for (const sub of subscribers[name] || []) {
      sub(value, prev);
    }
  }

  function subscribe(name, callback) {
    if (!subscribers[name]) subscribers[name] = [];
    subscribers[name].push(callback);
  }

  // Initialize signals from server-rendered data
  function initSignals() {
    const el = document.getElementById('orv-signals');
    if (!el) return;
    try {
      const data = JSON.parse(el.textContent);
      for (const [name, value] of Object.entries(data)) {
        createSignal(name, value);
      }
    } catch (_) { /* ignore parse errors */ }
  }

  // Bind event handlers from data-orv-on-* attributes
  function bindEvents() {
    document.querySelectorAll('[data-orv-on]').forEach(el => {
      const handlers = el.getAttribute('data-orv-on');
      if (!handlers) return;
      try {
        const parsed = JSON.parse(handlers);
        for (const [event, action] of Object.entries(parsed)) {
          el.addEventListener(event, () => {
            executeAction(action);
          });
        }
      } catch (_) { /* ignore parse errors */ }
    });
  }

  // Execute a signal action (e.g., "count += 1", "count = 0")
  function executeAction(action) {
    const assignMatch = action.match(/^(\w+)\s*=\s*(.+)$/);
    const addMatch = action.match(/^(\w+)\s*\+=\s*(.+)$/);
    const subMatch = action.match(/^(\w+)\s*-=\s*(.+)$/);

    if (addMatch) {
      const [, name, expr] = addMatch;
      const current = getSignal(name);
      setSignal(name, current + parseValue(expr));
    } else if (subMatch) {
      const [, name, expr] = subMatch;
      const current = getSignal(name);
      setSignal(name, current - parseValue(expr));
    } else if (assignMatch) {
      const [, name, expr] = assignMatch;
      setSignal(name, parseValue(expr));
    }
  }

  function parseValue(expr) {
    expr = expr.trim();
    if (expr === 'true') return true;
    if (expr === 'false') return false;
    if (expr === 'void' || expr === 'null') return null;
    const num = Number(expr);
    if (!isNaN(num)) return num;
    // Check if it's a signal reference
    if (signals.hasOwnProperty(expr)) return signals[expr];
    // String literal
    if ((expr.startsWith('"') && expr.endsWith('"')) ||
        (expr.startsWith("'") && expr.endsWith("'"))) {
      return expr.slice(1, -1);
    }
    return expr;
  }

  // Bind reactive text nodes: elements with data-orv-text="signalName"
  function bindTextNodes() {
    document.querySelectorAll('[data-orv-text]').forEach(el => {
      const signalName = el.getAttribute('data-orv-text');
      // Set initial value
      if (signals.hasOwnProperty(signalName)) {
        el.textContent = String(signals[signalName]);
      }
      // Subscribe to changes
      subscribe(signalName, (value) => {
        el.textContent = String(value);
      });
    });
  }

  // Bind reactive attributes: data-orv-bind-attr="signalName"
  function bindAttributes() {
    document.querySelectorAll('[data-orv-bind]').forEach(el => {
      const bindings = el.getAttribute('data-orv-bind');
      try {
        const parsed = JSON.parse(bindings);
        for (const [attr, signalName] of Object.entries(parsed)) {
          if (signals.hasOwnProperty(signalName)) {
            el.setAttribute(attr, String(signals[signalName]));
          }
          subscribe(signalName, (value) => {
            el.setAttribute(attr, String(value));
          });
        }
      } catch (_) { /* ignore */ }
    });
  }

  // Conditional rendering: data-orv-if="signalName"
  function bindConditionals() {
    document.querySelectorAll('[data-orv-if]').forEach(el => {
      const signalName = el.getAttribute('data-orv-if');
      const update = (value) => {
        el.style.display = value ? '' : 'none';
      };
      if (signals.hasOwnProperty(signalName)) {
        update(signals[signalName]);
      }
      subscribe(signalName, update);
    });
  }

  // Boot
  function init() {
    initSignals();
    bindEvents();
    bindTextNodes();
    bindAttributes();
    bindConditionals();
  }

  // Run on DOM ready
  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', init);
  } else {
    init();
  }

  return { createSignal, getSignal, setSignal, subscribe };
})();
"#
    .to_owned()
}

/// Convert a name to a URL-safe slug.
fn slugify(name: &str) -> String {
    name.chars()
        .map(|c| {
            if c.is_alphanumeric() {
                c.to_ascii_lowercase()
            } else {
                '-'
            }
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_sanitize_js_name() {
        assert_eq!(sanitize_js_name("getUsers"), "getUsers");
        assert_eq!(sanitize_js_name("get-users"), "get_users");
        assert_eq!(sanitize_js_name("api.users"), "api_users");
    }

    #[test]
    fn test_parameterized_path() {
        assert_eq!(
            generate_parameterized_path("/users/:id"),
            "`/users/${params.id}`"
        );
        assert_eq!(
            generate_parameterized_path("/users/:user_id/posts/:post_id"),
            "`/users/${params.user_id}/posts/${params.post_id}`"
        );
        assert_eq!(generate_parameterized_path("/api/health"), "`/api/health`");
    }

    #[test]
    fn test_slugify() {
        assert_eq!(slugify("HomePage"), "homepage");
        assert_eq!(slugify("user profile"), "user-profile");
        assert_eq!(slugify("API_v2"), "api-v2");
    }

    #[test]
    fn test_generate_fetch_bridge_empty() {
        let graph = WorkspaceGraph {
            entry: "main.orv".to_owned(),
            modules: Vec::new(),
            dependencies: Vec::new(),
        };
        let code = generate_fetch_bridge(&graph);
        assert!(code.contains("Auto-generated"));
        // No actual functions generated
        assert!(!code.contains("export async function"));
    }
}
