//! Build output emitter for the orv compiler.
//!
//! Generates the `dist/` directory structure:
//! ```text
//! dist/
//! ├── server.rs          (generated Rust server source)
//! ├── public/
//! │   ├── index.html     (static HTML from @html pages)
//! │   └── app.js         (client-side fetch bridges)
//! └── manifest.json      (build manifest)
//! ```

use std::fmt::Write;
use std::fs;
use std::path::{Path, PathBuf};

use orv_project::WorkspaceGraph;

use crate::pipeline::WorkspaceHir;

/// Build manifest describing all output artifacts.
#[derive(Debug, Clone, serde::Serialize)]
pub struct BuildManifest {
    pub version: String,
    pub entry: String,
    pub outputs: Vec<BuildOutput>,
    pub routes: Vec<RouteManifestEntry>,
    pub pages: Vec<PageManifestEntry>,
}

#[derive(Debug, Clone, serde::Serialize)]
pub struct BuildOutput {
    pub kind: String,
    pub path: String,
}

#[derive(Debug, Clone, serde::Serialize)]
pub struct RouteManifestEntry {
    pub method: String,
    pub path: String,
}

#[derive(Debug, Clone, serde::Serialize)]
pub struct PageManifestEntry {
    pub owner: String,
    pub domain: String,
    pub html_file: String,
}

/// Generate client-side fetch bridge code for internal routes.
///
/// For each `FetchEdge` that references a route target, generates a typed
/// fetch function:
/// ```js
/// export async function target_fetch(params = {}) {
///   const response = await fetch('/api/users', { method: 'GET' });
///   return response.json();
/// }
/// ```
pub fn generate_fetch_bridge(graph: &WorkspaceGraph) -> String {
    let mut code = String::new();
    code.push_str("// Auto-generated by orv compiler - do not edit\n");
    code.push_str("// Fetch bridges for internal route references\n\n");

    for module in &graph.modules {
        for fetch in &module.fetches {
            // Find the matching route by path (the fetch target is the route path)
            let route = module
                .routes
                .iter()
                .find(|r| r.path == fetch.target || r.action == fetch.target);

            if let Some(route) = route {
                let fn_name = sanitize_js_name(&fetch.target);
                let method = &route.method;
                let path = &route.path;

                // Check if path has parameters
                let has_params = path.contains(':');

                let _ = writeln!(
                    code,
                    "export async function {fn_name}_fetch(params = {{}}) {{"
                );

                if has_params {
                    // Generate path with parameter substitution
                    let js_path = generate_parameterized_path(path);
                    let _ = writeln!(code, "  const url = {js_path};");
                } else {
                    let _ = writeln!(code, "  const url = '{path}';");
                }

                let _ = writeln!(code, "  const options = {{ method: '{method}' }};");

                // Add body for POST/PUT/PATCH
                if matches!(method.as_str(), "POST" | "PUT" | "PATCH") {
                    code.push_str(
                        "  if (params.body !== undefined) {\n\
                         \x20   options.headers = { 'Content-Type': 'application/json' };\n\
                         \x20   options.body = JSON.stringify(params.body);\n\
                         \x20 }\n",
                    );
                }

                code.push_str("  const response = await fetch(url, options);\n");
                code.push_str("  if (!response.ok) throw new Error(`HTTP ${response.status}`);\n");

                // Return type based on route action
                code.push_str("  return response.json();\n");
                let _ = writeln!(code, "}}\n");
            }
        }
    }

    code
}

/// Generate a parameterized path template for JavaScript.
/// `/users/:id/posts/:post_id` → `` `/users/${params.id}/posts/${params.post_id}` ``
fn generate_parameterized_path(path: &str) -> String {
    let mut result = String::from("`");
    for segment in path.split('/') {
        if segment.is_empty() {
            continue;
        }
        result.push('/');
        if let Some(param_name) = segment.strip_prefix(':') {
            let _ = write!(result, "${{params.{param_name}}}");
        } else {
            result.push_str(segment);
        }
    }
    result.push('`');
    result
}

/// Sanitize a name for use as a JavaScript identifier.
fn sanitize_js_name(name: &str) -> String {
    name.chars()
        .map(|c| {
            if c.is_alphanumeric() || c == '_' {
                c
            } else {
                '_'
            }
        })
        .collect()
}

/// Pre-render output from a WorkspaceHir, including any client island assets.
struct PrerenderOutputs {
    html: String,
    css: String,
    handlers_js: String,
    has_islands: bool,
}

/// Render in-memory HTML content, CSS, and island handlers JS from a
/// WorkspaceHir using the runtime.
fn render_html_and_css_from_hir(hir: &WorkspaceHir) -> PrerenderOutputs {
    use orv_runtime::runner::prerender_workspace;

    match prerender_workspace(&hir.modules) {
        Ok(result) => PrerenderOutputs {
            html: result.html,
            css: result.css,
            handlers_js: result.handlers_js,
            has_islands: !result.islands.is_empty(),
        },
        Err(_) => PrerenderOutputs {
            html: String::new(),
            css: String::new(),
            handlers_js: String::new(),
            has_islands: false,
        },
    }
}

/// Emit the build output to the given directory.
pub fn emit_build_output(
    graph: &WorkspaceGraph,
    entry_name: &str,
    output_dir: &Path,
    hir: Option<&WorkspaceHir>,
) -> Result<EmitResult, EmitError> {
    fs::create_dir_all(output_dir).map_err(|e| EmitError::Io(e.to_string()))?;

    let public_dir = output_dir.join("public");
    fs::create_dir_all(&public_dir).map_err(|e| EmitError::Io(e.to_string()))?;

    let mut outputs = Vec::new();
    let mut page_entries = Vec::new();

    // Resolve full route paths using dependency + define return_path info
    let resolved_routes = resolve_workspace_routes(graph);
    let route_entries: Vec<RouteManifestEntry> = resolved_routes
        .iter()
        .map(|r| RouteManifestEntry {
            method: r.method.clone(),
            path: r.path.clone(),
        })
        .collect();

    for module in &graph.modules {
        for page in &module.pages {
            page_entries.push(PageManifestEntry {
                owner: page.owner.clone(),
                domain: page.domain.clone(),
                html_file: format!("public/{}.html", slugify(&page.owner)),
            });
        }
    }

    // Generate client runtime (signals + event binding)
    let runtime_code = generate_client_runtime();
    let runtime_path = public_dir.join("orv-runtime.js");
    fs::write(&runtime_path, &runtime_code).map_err(|e| EmitError::Io(e.to_string()))?;
    outputs.push(BuildOutput {
        kind: "client-runtime".to_owned(),
        path: "public/orv-runtime.js".to_owned(),
    });

    // Generate fetch bridge
    let fetch_code = generate_fetch_bridge(graph);
    if !fetch_code.trim().is_empty() && fetch_code.lines().count() > 3 {
        let js_path = public_dir.join("app.js");
        fs::write(&js_path, &fetch_code).map_err(|e| EmitError::Io(e.to_string()))?;
        outputs.push(BuildOutput {
            kind: "fetch-bridge".to_owned(),
            path: "public/app.js".to_owned(),
        });
    }

    // Pre-render HTML/CSS from WorkspaceHir if available
    let prerender = if let Some(hir) = hir {
        render_html_and_css_from_hir(hir)
    } else {
        PrerenderOutputs {
            html: String::new(),
            css: String::new(),
            handlers_js: String::new(),
            has_islands: false,
        }
    };

    // Emit client island handlers JS only when there are islands. Zero-island
    // pages get no extra JS, preserving the "no JS unless needed" property.
    if prerender.has_islands && !prerender.handlers_js.is_empty() {
        let handlers_path = public_dir.join("orv-handlers.js");
        fs::write(&handlers_path, &prerender.handlers_js)
            .map_err(|e| EmitError::Io(e.to_string()))?;
        outputs.push(BuildOutput {
            kind: "client-handlers".to_owned(),
            path: "public/orv-handlers.js".to_owned(),
        });
    }

    // Generate server binary from workspace routes
    if !route_entries.is_empty() {
        let server_source = generate_server_source_from_routes(
            &resolved_routes,
            &prerender.html,
            &prerender.css,
        );
        let server_rs_path = output_dir.join("server.rs");
        fs::write(&server_rs_path, &server_source).map_err(|e| EmitError::Io(e.to_string()))?;
        outputs.push(BuildOutput {
            kind: "server-source".to_owned(),
            path: "server.rs".to_owned(),
        });

        let binary_name = format!("orv-app{}", std::env::consts::EXE_SUFFIX);
        let binary_path = output_dir.join(&binary_name);
        let status = std::process::Command::new("rustc")
            .arg(&server_rs_path)
            .arg("-O")
            .arg("-o")
            .arg(&binary_path)
            .status()
            .map_err(|e| EmitError::Io(e.to_string()))?;
        if status.success() {
            outputs.push(BuildOutput {
                kind: "binary".to_owned(),
                path: binary_name,
            });
        } else {
            eprintln!("warning: rustc failed to compile server binary; source still available at server.rs");
        }
    }

    // Generate manifest
    let manifest = BuildManifest {
        version: "0.1.0".to_owned(),
        entry: entry_name.to_owned(),
        outputs: outputs.clone(),
        routes: route_entries,
        pages: page_entries,
    };

    let manifest_path = output_dir.join("manifest.json");
    let manifest_json =
        serde_json::to_string_pretty(&manifest).map_err(|e| EmitError::Io(e.to_string()))?;
    fs::write(&manifest_path, &manifest_json).map_err(|e| EmitError::Io(e.to_string()))?;

    outputs.push(BuildOutput {
        kind: "manifest".to_owned(),
        path: "manifest.json".to_owned(),
    });

    Ok(EmitResult {
        output_dir: output_dir.to_owned(),
        manifest_path,
        outputs,
    })
}

/// Result of a build emission.
#[derive(Debug)]
pub struct EmitResult {
    pub output_dir: PathBuf,
    pub manifest_path: PathBuf,
    pub outputs: Vec<BuildOutput>,
}

#[derive(Debug, thiserror::Error)]
pub enum EmitError {
    #[error("I/O error: {0}")]
    Io(String),
}

/// Generate the minimal client-side runtime for the island hydration model.
///
/// On boot the runtime:
///   1. Reads `<script type="application/json" id="orv-islands">` for the
///      hydration payload (per-island `props` and `sigs`).
///   2. Walks every element with `data-orv-i="iN"` and creates a reactive
///      `state` proxy from that island's payload.
///   3. Wires up `data-orv-text="iN:name"` spans so they re-render when the
///      named signal changes.
///   4. Binds `data-orv-h="iN:event:hM,..."` element handlers via the
///      pre-emitted `window.__orvHandlers[iN][hM]` function.
///
/// Importantly, no signal/handler source ever crosses the wire as plain text
/// — handlers are emitted as a separate compiled module by the SSR pass and
/// invoked by id, while the inline payload only contains primitive values.
pub fn generate_client_runtime() -> String {
    orv_runtime::island::client_runtime_source()
}

/// A resolved route with its full path (including cross-module prefixes).
struct ResolvedRoute {
    method: String,
    path: String,
    action: String,
}

/// Resolve full route paths across modules by combining:
/// - route group prefixes (from `@route /api { @Health @User }` via `route_group_calls`)
/// - define return_path (from `define X() -> @route /path`)
/// - dependency relationships
fn resolve_workspace_routes(graph: &WorkspaceGraph) -> Vec<ResolvedRoute> {
    use std::collections::HashMap;

    // Map: define_name → module_name (which module exports which define)
    let mut define_to_module: HashMap<&str, &str> = HashMap::new();
    for module in &graph.modules {
        for define in &module.defines {
            define_to_module.insert(&define.name, &module.module);
        }
    }

    // Map: define_name → return_path
    let mut define_to_path: HashMap<&str, Option<&str>> = HashMap::new();
    for module in &graph.modules {
        for define in &module.defines {
            define_to_path.insert(&define.name, define.return_path.as_deref());
        }
    }

    // Build prefix for each define by walking route_group_calls recursively.
    // A define's prefix = the route_group prefix it was called in + parent define's prefix.
    //
    // Example for project-e2e:
    //   main.orv: route_group_calls = [("/api", "Health"), ("/api", "User")]
    //     → Health gets prefix "/api", User gets prefix "/api"
    //   user/index.orv: User defines @route /user { @List @Delete }
    //     → route_group_calls = [("/user", "List"), ("/user", "Delete")]
    //     → List gets prefix "/api" + "/user" = "/api/user"
    //     → Delete gets prefix "/api" + "/user" = "/api/user"
    let mut define_prefix: HashMap<&str, String> = HashMap::new();

    // BFS: seed only from the entry module's route_group_calls
    let mut queue: std::collections::VecDeque<(&str, String)> = std::collections::VecDeque::new();

    if let Some(entry_module) = graph.modules.iter().find(|m| m.module == graph.entry) {
        for call in &entry_module.route_group_calls {
            queue.push_back((&call.define_name, call.prefix.clone()));
        }
    }

    // Process queue — each define gets its accumulated prefix
    while let Some((define_name, prefix)) = queue.pop_front() {
        if define_prefix.contains_key(define_name) {
            continue;
        }
        define_prefix.insert(define_name, prefix.clone());

        // If this define's module has its own route_group_calls, propagate
        if let Some(&module_name) = define_to_module.get(define_name)
            && let Some(module) = graph.modules.iter().find(|m| m.module == module_name)
        {
            for call in &module.route_group_calls {
                let child_prefix = format!("{}{}", prefix, call.prefix);
                queue.push_back((&call.define_name, child_prefix));
            }
        }
    }

    // Now build module_prefix: for each module, find the prefix from its defines
    let mut module_prefix: HashMap<&str, String> = HashMap::new();
    for module in &graph.modules {
        if module.module == graph.entry {
            continue;
        }
        // Find the best prefix: look at defines in this module that have a prefix
        let mut best_prefix = String::new();
        for define in &module.defines {
            if let Some(prefix) = define_prefix.get(define.name.as_str()) {
                // The define's prefix is the route group prefix it was called in.
                // The define's own return_path is already baked into the module's routes.
                best_prefix = prefix.clone();
                break;
            }
        }
        module_prefix.insert(&module.module, best_prefix);
    }

    // Collect all routes with resolved full paths
    let mut routes = Vec::new();
    for module in &graph.modules {
        let prefix = module_prefix.get(module.module.as_str()).cloned().unwrap_or_default();
        for route in &module.routes {
            let full_path = if route.path == "*" {
                "*".to_owned()
            } else {
                format!("{}{}", prefix, route.path)
            };
            routes.push(ResolvedRoute {
                method: route.method.clone(),
                path: full_path,
                action: route.action.clone(),
            });
        }
    }

    routes
}

/// Generate a standalone Rust HTTP server source from resolved routes.
///
/// `rendered_html` / `rendered_css` come from the WorkspaceHir pre-render pass.
/// When non-empty, `html-serve` routes embed the real rendered page instead of a stub.
///
/// `rendered_css` is intentionally unused here: the runtime's
/// `inject_design_and_islands` already tree-shakes and minifies design tokens
/// directly into the prerendered HTML, so re-emitting the raw CSS would just
/// duplicate (and unminify) the style block.
fn generate_server_source_from_routes(
    routes: &[ResolvedRoute],
    rendered_html: &str,
    _rendered_css: &str,
) -> String {
    let mut route_arms = String::new();
    let mut wildcard_arms = String::new();

    let final_html = if rendered_html.is_empty() {
        String::new()
    } else {
        rendered_html.to_owned()
    };

    for route in routes {
        let method = &route.method;
        let path = &route.path;

        // Determine response based on action
        let (status, content_type, body) = match route.action.as_str() {
            "json-respond" => (200, "application/json", r#"{"status":"ok"}"#.to_owned()),
            "html-serve" => {
                if !final_html.is_empty() {
                    (200, "text/html; charset=utf-8", final_html.clone())
                } else {
                    (
                        200,
                        "text/html; charset=utf-8",
                        "<html><body>orv app</body></html>".to_owned(),
                    )
                }
            }
            _ => (200, "application/json", format!("{{\"route\":\"{path}\"}}")),
        };

        if path == "*" {
            let _ = writeln!(
                wildcard_arms,
                "        (\"{method}\", _) => respond(&stream, {status}, \"{content_type}\", {:?}),",
                body
            );
        } else if path.contains(':') {
            // Path with parameters — match by prefix and segment count
            let segments: Vec<&str> = path.split('/').filter(|s| !s.is_empty()).collect();
            let seg_count = segments.len();
            let prefix: String = segments.iter()
                .take_while(|s| !s.starts_with(':'))
                .fold(String::new(), |acc, s| format!("{acc}/{s}"));
            let _ = writeln!(
                route_arms,
                "        (\"{method}\", p) if p.starts_with(\"{prefix}/\") && p.split('/').filter(|s| !s.is_empty()).count() == {seg_count} => respond(&stream, {status}, \"{content_type}\", {:?}),",
                body
            );
        } else {
            let _ = writeln!(
                route_arms,
                "        (\"{method}\", \"{path}\") => respond(&stream, {status}, \"{content_type}\", {:?}),",
                body
            );
        }
    }

    // Append wildcards after specific routes
    route_arms.push_str(&wildcard_arms);

    format!(
        r##"//! Auto-generated by orv compiler — do not edit.
use std::io::{{BufRead, BufReader, Write}};
use std::net::TcpListener;

fn main() {{
    let port = std::env::var("PORT").ok().and_then(|p| p.parse().ok()).unwrap_or(3000u16);
    let addr = format!("127.0.0.1:{{}}", port);
    let listener = TcpListener::bind(&addr).expect("failed to bind");
    eprintln!("orv-app listening on http://{{}}", addr);

    for stream in listener.incoming() {{
        let Ok(stream) = stream else {{ continue }};
        let _ = stream.set_read_timeout(Some(std::time::Duration::from_secs(30)));
        let mut reader = BufReader::new(&stream);
        let mut request_line = String::new();
        if reader.read_line(&mut request_line).unwrap_or(0) == 0 {{ continue }}
        let parts: Vec<&str> = request_line.split_whitespace().collect();
        if parts.len() < 2 {{ continue }}
        let method = parts[0];
        let path = parts[1].split('?').next().unwrap_or(parts[1]);

        // Drain headers
        loop {{
            let mut line = String::new();
            if reader.read_line(&mut line).unwrap_or(0) == 0 || line.trim().is_empty() {{ break }}
        }}

        match (method, path) {{
{route_arms}        _ => respond(&stream, 404, "application/json", "{{\"error\":\"not found\"}}"),
        }}
    }}
}}

fn respond(mut stream: &std::net::TcpStream, status: u16, content_type: &str, body: &str) {{
    let status_text = match status {{
        200 => "OK", 201 => "Created", 204 => "No Content",
        400 => "Bad Request", 401 => "Unauthorized", 404 => "Not Found",
        500 => "Internal Server Error", _ => "OK",
    }};
    let response = format!(
        "HTTP/1.1 {{}} {{}}\r\nContent-Type: {{}}\r\nContent-Length: {{}}\r\nConnection: close\r\n\r\n{{}}",
        status, status_text, content_type, body.len(), body
    );
    let _ = stream.write_all(response.as_bytes());
}}
"##
    )
}

/// Convert a name to a URL-safe slug.
fn slugify(name: &str) -> String {
    name.chars()
        .map(|c| {
            if c.is_alphanumeric() {
                c.to_ascii_lowercase()
            } else {
                '-'
            }
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_sanitize_js_name() {
        assert_eq!(sanitize_js_name("getUsers"), "getUsers");
        assert_eq!(sanitize_js_name("get-users"), "get_users");
        assert_eq!(sanitize_js_name("api.users"), "api_users");
    }

    #[test]
    fn test_parameterized_path() {
        assert_eq!(
            generate_parameterized_path("/users/:id"),
            "`/users/${params.id}`"
        );
        assert_eq!(
            generate_parameterized_path("/users/:user_id/posts/:post_id"),
            "`/users/${params.user_id}/posts/${params.post_id}`"
        );
        assert_eq!(generate_parameterized_path("/api/health"), "`/api/health`");
    }

    #[test]
    fn test_slugify() {
        assert_eq!(slugify("HomePage"), "homepage");
        assert_eq!(slugify("user profile"), "user-profile");
        assert_eq!(slugify("API_v2"), "api-v2");
    }

    #[test]
    fn test_generate_fetch_bridge_empty() {
        let graph = WorkspaceGraph {
            entry: "main.orv".to_owned(),
            modules: Vec::new(),
            dependencies: Vec::new(),
        };
        let code = generate_fetch_bridge(&graph);
        assert!(code.contains("Auto-generated"));
        // No actual functions generated
        assert!(!code.contains("export async function"));
    }
}
